version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stockflow_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: mysql
      DB_DATABASE: stockflow
      DB_USERNAME: admin
      DB_PASSWORD: admin
      APP_ENV: production
      APP_KEY: base64:cyJvOKMPS0GaSsRicwRtt1t3tJv4k1BJ+p4ZVo6tmCc= # Generar con: php artisan key:geerate --shnow
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge