version: '3.8'

services:
  # Base de datos MySQL
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  # Backend Laravel
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    environment:
      - DB_HOST=database
      - DB_DATABASE=stockflow
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    depends_on:
      - database
    networks:
      - app_network

  # Nginx para Laravel
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./backend:/var/www
      - ./nginx-laravel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app_network

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge