version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stockflow-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - stocknet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stockflow-phpmyadmin
    restart: always
    ports:
      - "8080:8080"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - stocknet

networks:
  stocknet:
    driver: bridge
