version: '3.8'

services:
  # Base de datos MySQL
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-stockflow}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Laravel
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY:-}
      - APP_URL=${APP_URL:-http://localhost:9000}
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-stockflow}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin}
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - database
    networks:
      - app_network

  # Nginx para Laravel
  webserver:
    build:
      context: .
      dockerfile: backend/nginx.Dockerfile
    container_name: nginx_server
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    ports:
      - "${BACKEND_PORT:-9000}:80"
    depends_on:
      - backend
    networks:
      - app_network
    # Comando para verificar la configuración
    command: >
      sh -c "nginx -t && nginx -g 'daemon off;'"

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_app
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - webserver
    networks:
      - app_network
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:9000}
      - NODE_OPTIONS=--max_old_space_size=4096

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge